Homework2
EnoticSho/network_chat pull request #3
Opened 2022-04-27 01:19 UTC by EnoticSho

база данных

2022-05-01 06:11 UTC, efserg requested changes
Переделывайте на нормальное использование PreparedStatement

2022-05-01 06:11 UTC, efserg commented on src/main/java/com/example/network_chat/server/ChatServer.java
> +        try (PreparedStatement statement = connection.prepareStatement(String.format("UPDATE users SET nick = '"+ param +"' WHERE nick = ?"))){
Это сразу не принимается.
Несмотря на то, что вы используете PreparedStatement , вы оставляете лазейку для sql-injection своей конкатенацией в запросе. Переделывайте

2022-05-04 05:47 UTC, EnoticSho commented on src/main/java/com/example/network_chat/server/ChatServer.java
> +        try (PreparedStatement statement = connection.prepareStatement(String.format("UPDATE users SET nick = '"+ param +"' WHERE nick = ?"))){
Изменил запрос!

2022-05-04 16:36 UTC, efserg approved these changes

2022-05-04 19:57 UTC, closed without merging